---
apiVersion: monitoring.healthchecks.io/v1alpha1
kind: Check
metadata:
  name: check-sample
spec:
  schedule: "*/10 * * * *"
  timezone: "Europe/Stockholm"
  gracePeriod: 120
  channels:
    - "email/Email Me"
    - "email/Email Them"
    - "webhook"
  tags:
    - healthchecksio-operator
    - prod

---
apiVersion: monitoring.healthchecks.io/v1alpha1
kind: Check
metadata:
  name: check-sample-two
spec:
  timeout: 3600
  gracePeriod: 120
  channels:
    - "webhook"
  tags:
    - healthchecksio-operator
    - dev
